-- MySQL Script generated by MySQL Workbench
-- jue 16 mar 2023 06:48:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`level_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`level_access` (
  `idlevel_access` INT NOT NULL AUTO_INCREMENT,
  `access_code` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idlevel_access`),
  UNIQUE INDEX `access_code_UNIQUE` (`access_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shopping_cart` (
  `id_shopping_cart` INT NOT NULL AUTO_INCREMENT,
  `full_value` DOUBLE NOT NULL,
  PRIMARY KEY (`id_shopping_cart`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  `address` VARCHAR(45) NOT NULL,
  `level_access_idlevel_access` INT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `shopping_cart_id_shopping_cart` INT NOT NULL,
  PRIMARY KEY (`idusers`, `level_access_idlevel_access`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_users_level_access1_idx` (`level_access_idlevel_access` ASC) VISIBLE,
  INDEX `fk_users_shopping_cart1_idx` (`shopping_cart_id_shopping_cart` ASC) VISIBLE,
  CONSTRAINT `fk_users_level_access1`
    FOREIGN KEY (`level_access_idlevel_access`)
    REFERENCES `mydb`.`level_access` (`idlevel_access`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_shopping_cart1`
    FOREIGN KEY (`shopping_cart_id_shopping_cart`)
    REFERENCES `mydb`.`shopping_cart` (`id_shopping_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `price` DOUBLE NOT NULL,
  `isAvailable` TINYINT NOT NULL,
  `limit_date` DATE NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_category` (
  `product_idproduct` INT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`product_idproduct`, `category_idcategory`),
  INDEX `fk_product_has_category_category1_idx` (`category_idcategory` ASC) VISIBLE,
  INDEX `fk_product_has_category_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(200) NOT NULL,
  `product_idproduct` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  `users_level_access_idlevel_access` INT NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comments_product1_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`users_idusers` ASC, `users_level_access_idlevel_access` ASC) VISIBLE,
  CONSTRAINT `fk_comments_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_idusers` , `users_level_access_idlevel_access`)
    REFERENCES `mydb`.`users` (`idusers` , `level_access_idlevel_access`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `id_favorites` INT NOT NULL AUTO_INCREMENT,
  `users_idusers` INT NOT NULL,
  `users_level_access_idlevel_access` INT NOT NULL,
  PRIMARY KEY (`id_favorites`),
  INDEX `fk_favorites_users1_idx` (`users_idusers` ASC, `users_level_access_idlevel_access` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_idusers` , `users_level_access_idlevel_access`)
    REFERENCES `mydb`.`users` (`idusers` , `level_access_idlevel_access`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorites_has_products` (
  `favorites_id_favorites` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`favorites_id_favorites`, `products_idproduct`),
  INDEX `fk_favorites_has_products_products1_idx` (`products_idproduct` ASC) VISIBLE,
  INDEX `fk_favorites_has_products_favorites1_idx` (`favorites_id_favorites` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_has_products_favorites1`
    FOREIGN KEY (`favorites_id_favorites`)
    REFERENCES `mydb`.`favorites` (`id_favorites`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_has_products_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shopping_cart_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shopping_cart_has_products` (
  `shopping_cart_id_shopping_cart` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`shopping_cart_id_shopping_cart`, `products_idproduct`),
  INDEX `fk_shopping_cart_has_products_products1_idx` (`products_idproduct` ASC) VISIBLE,
  INDEX `fk_shopping_cart_has_products_shopping_cart1_idx` (`shopping_cart_id_shopping_cart` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_has_products_shopping_cart1`
    FOREIGN KEY (`shopping_cart_id_shopping_cart`)
    REFERENCES `mydb`.`shopping_cart` (`id_shopping_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_has_products_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `mydb`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coupons` (
  `id_coupon` INT NOT NULL AUTO_INCREMENT,
  `coupon_value` DOUBLE NOT NULL,
  `security_code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL,
  `is_active` TINYINT NOT NULL,
  `limit_date` DATE NOT NULL,
  `users_idusers` INT NOT NULL,
  `users_level_access_idlevel_access` INT NOT NULL,
  PRIMARY KEY (`id_coupon`),
  UNIQUE INDEX `security_code_UNIQUE` (`security_code` ASC) VISIBLE,
  INDEX `fk_coupons_users1_idx` (`users_idusers` ASC, `users_level_access_idlevel_access` ASC) VISIBLE,
  CONSTRAINT `fk_coupons_users1`
    FOREIGN KEY (`users_idusers` , `users_level_access_idlevel_access`)
    REFERENCES `mydb`.`users` (`idusers` , `level_access_idlevel_access`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
